package Configuracion;
// Generated 05/12/2012 11:15:21 by Hibernate Tools 3.2.1.GA



/**
 * FollowerNotification generated by hbm2java
 */
public class FollowerNotification  extends Notification {


     private int id_follower;

    public FollowerNotification() {
    }

    public FollowerNotification(int id_follower) {
        this.id_follower = id_follower;
    }
     
     
     

    public int getId_follower() {
        return id_follower;
    }

    public void setId_follower(int id_follower) {
        this.id_follower = id_follower;
    }
     
     
     



}


