package Configuracion;
// Generated 05/12/2012 11:15:21 by Hibernate Tools 3.2.1.GA



/**
 * Follower generated by hbm2java
 */
public class Follower  implements java.io.Serializable {


     private Integer idRelation;
     private Integer idFollower;
     private Integer idFollowed;

    public Follower() {
    }

    public Follower(Integer idFollower, Integer idFollowed) {
       this.idFollower = idFollower;
       this.idFollowed = idFollowed;
    }
   
    public Integer getIdRelation() {
        return this.idRelation;
    }
    
    public void setIdRelation(Integer idRelation) {
        this.idRelation = idRelation;
    }
    public Integer getIdFollower() {
        return this.idFollower;
    }
    
    public void setIdFollower(Integer idFollower) {
        this.idFollower = idFollower;
    }
    public Integer getIdFollowed() {
        return this.idFollowed;
    }
    
    public void setIdFollowed(Integer idFollowed) {
        this.idFollowed = idFollowed;
    }




}


