package Configuracion;
// Generated 05/12/2012 11:15:21 by Hibernate Tools 3.2.1.GA



/**
 * MessageNotification generated by hbm2java
 */
public class MessageNotification  extends Notification {


  private int id_message;

    public MessageNotification() {
    }

    public MessageNotification(int id_message) {
        this.id_message = id_message;
    }

  
    
  
  
    public int getId_message() {
        return id_message;
    }

    public void setId_message(int id_message) {
        this.id_message = id_message;
    }
  
  
  




}


