package Configuracion;
// Generated 05/12/2012 11:15:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer idMessage;
     private Location location;
     private Topic topic;
     private User user;
     private Date date;
     private String body;
     private String messagecol;
     private Set<Reference> references = new HashSet<Reference>(0);
     private Set<MessageNotification> messageNotifications = new HashSet<MessageNotification>(0);

    public Message() {
    }

    public Message(Location location, Topic topic, User user, Date date, String body, String messagecol, Set<Reference> references, Set<MessageNotification> messageNotifications) {
       this.location = location;
       this.topic = topic;
       this.user = user;
       this.date = date;
       this.body = body;
       this.messagecol = messagecol;
       this.references = references;
       this.messageNotifications = messageNotifications;
    }
   
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(Topic topic) {
        this.topic = topic;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public String getMessagecol() {
        return this.messagecol;
    }
    
    public void setMessagecol(String messagecol) {
        this.messagecol = messagecol;
    }
    public Set<Reference> getReferences() {
        return this.references;
    }
    
    public void setReferences(Set<Reference> references) {
        this.references = references;
    }
    public Set<MessageNotification> getMessageNotifications() {
        return this.messageNotifications;
    }
    
    public void setMessageNotifications(Set<MessageNotification> messageNotifications) {
        this.messageNotifications = messageNotifications;
    }




}


