package Configuracion;
// Generated 05/12/2012 11:15:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Location location;
     private String userName;
     private String passwords;
     private String email;
     private String firstName;
     private String lastName;
     private Integer biography;
     private String pathPhoto;
     private String usercol;
     private Set<FollowerNotification> followerNotificationsForIdFollower = new HashSet<FollowerNotification>(0);
     private Set<Message> messages = new HashSet<Message>(0);
     private Set<MessageNotification> messageNotifications = new HashSet<MessageNotification>(0);
     private Set<Reference> references = new HashSet<Reference>(0);
     private Set<FollowerNotification> followerNotificationsForIdUser = new HashSet<FollowerNotification>(0);

    public User() {
    }

    public User(Location location, String userName, String passwords, String email, String firstName, String lastName, Integer biography, String pathPhoto, String usercol, Set<FollowerNotification> followerNotificationsForIdFollower, Set<Message> messages, Set<MessageNotification> messageNotifications, Set<Reference> references, Set<FollowerNotification> followerNotificationsForIdUser) {
       this.location = location;
       this.userName = userName;
       this.passwords = passwords;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.biography = biography;
       this.pathPhoto = pathPhoto;
       this.usercol = usercol;
       this.followerNotificationsForIdFollower = followerNotificationsForIdFollower;
       this.messages = messages;
       this.messageNotifications = messageNotifications;
       this.references = references;
       this.followerNotificationsForIdUser = followerNotificationsForIdUser;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getBiography() {
        return this.biography;
    }
    
    public void setBiography(Integer biography) {
        this.biography = biography;
    }
    public String getPathPhoto() {
        return this.pathPhoto;
    }
    
    public void setPathPhoto(String pathPhoto) {
        this.pathPhoto = pathPhoto;
    }
    public String getUsercol() {
        return this.usercol;
    }
    
    public void setUsercol(String usercol) {
        this.usercol = usercol;
    }
    public Set<FollowerNotification> getFollowerNotificationsForIdFollower() {
        return this.followerNotificationsForIdFollower;
    }
    
    public void setFollowerNotificationsForIdFollower(Set<FollowerNotification> followerNotificationsForIdFollower) {
        this.followerNotificationsForIdFollower = followerNotificationsForIdFollower;
    }
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }
    public Set<MessageNotification> getMessageNotifications() {
        return this.messageNotifications;
    }
    
    public void setMessageNotifications(Set<MessageNotification> messageNotifications) {
        this.messageNotifications = messageNotifications;
    }
    public Set<Reference> getReferences() {
        return this.references;
    }
    
    public void setReferences(Set<Reference> references) {
        this.references = references;
    }
    public Set<FollowerNotification> getFollowerNotificationsForIdUser() {
        return this.followerNotificationsForIdUser;
    }
    
    public void setFollowerNotificationsForIdUser(Set<FollowerNotification> followerNotificationsForIdUser) {
        this.followerNotificationsForIdUser = followerNotificationsForIdUser;
    }




}


