package Model;
// Generated 04-dic-2012 11:46:29 by Hibernate Tools 3.2.1.GA



/**
 * FollowerNotification generated by hbm2java
 */
public class FollowerNotification  implements java.io.Serializable {


     private Integer idNotificationF;
     private Integer idUser;
     private Integer idFollower;

    public FollowerNotification() {
    }

    public FollowerNotification(Integer idUser, Integer idFollower) {
       this.idUser = idUser;
       this.idFollower = idFollower;
    }
   
    public Integer getIdNotificationF() {
        return this.idNotificationF;
    }
    
    public void setIdNotificationF(Integer idNotificationF) {
        this.idNotificationF = idNotificationF;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Integer getIdFollower() {
        return this.idFollower;
    }
    
    public void setIdFollower(Integer idFollower) {
        this.idFollower = idFollower;
    }




}


