package Model;
// Generated 04-dic-2012 11:46:29 by Hibernate Tools 3.2.1.GA



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer idLocation;
     private String name;

    public Location() {
    }

    public Location(String name) {
       this.name = name;
    }
   
    public Integer getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Integer idLocation) {
        this.idLocation = idLocation;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


