package Model;
// Generated 04-dic-2012 11:46:29 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer idMessage;
     private Date date;
     private Integer idUserCreator;
     private Integer location;
     private Integer topic;
     private String body;

    public Message() {
    }

    public Message(Date date, Integer idUserCreator, Integer location, Integer topic, String body) {
       this.date = date;
       this.idUserCreator = idUserCreator;
       this.location = location;
       this.topic = topic;
       this.body = body;
    }
   
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getIdUserCreator() {
        return this.idUserCreator;
    }
    
    public void setIdUserCreator(Integer idUserCreator) {
        this.idUserCreator = idUserCreator;
    }
    public Integer getLocation() {
        return this.location;
    }
    
    public void setLocation(Integer location) {
        this.location = location;
    }
    public Integer getTopic() {
        return this.topic;
    }
    
    public void setTopic(Integer topic) {
        this.topic = topic;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }




}


