package Model;
// Generated 04-dic-2012 11:46:29 by Hibernate Tools 3.2.1.GA



/**
 * MessageNotification generated by hbm2java
 */
public class MessageNotification  implements java.io.Serializable {


     private Integer idNotificationM;
     private Integer idUser;
     private Integer idMessage;

    public MessageNotification() {
    }

    public MessageNotification(Integer idUser, Integer idMessage) {
       this.idUser = idUser;
       this.idMessage = idMessage;
    }
   
    public Integer getIdNotificationM() {
        return this.idNotificationM;
    }
    
    public void setIdNotificationM(Integer idNotificationM) {
        this.idNotificationM = idNotificationM;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }




}


