package Model;
// Generated 04-dic-2012 11:46:29 by Hibernate Tools 3.2.1.GA



/**
 * Reference generated by hbm2java
 */
public class Reference  implements java.io.Serializable {


     private Integer idReference;
     private Integer idMessage;
     private Integer idUser;

    public Reference() {
    }

    public Reference(Integer idMessage, Integer idUser) {
       this.idMessage = idMessage;
       this.idUser = idUser;
    }
   
    public Integer getIdReference() {
        return this.idReference;
    }
    
    public void setIdReference(Integer idReference) {
        this.idReference = idReference;
    }
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }




}


