package Model;
// Generated 04-dic-2012 11:46:29 by Hibernate Tools 3.2.1.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String userName;
     private String passwords;
     private String email;
     private String firstName;
     private String lastName;
     private Integer idLocation;
     private Integer biography;
     private String pathPhoto;

    public User() {
    }

    public User(String userName, String passwords, String email, String firstName, String lastName, Integer idLocation, Integer biography, String pathPhoto) {
       this.userName = userName;
       this.passwords = passwords;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.idLocation = idLocation;
       this.biography = biography;
       this.pathPhoto = pathPhoto;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Integer idLocation) {
        this.idLocation = idLocation;
    }
    public Integer getBiography() {
        return this.biography;
    }
    
    public void setBiography(Integer biography) {
        this.biography = biography;
    }
    public String getPathPhoto() {
        return this.pathPhoto;
    }
    
    public void setPathPhoto(String pathPhoto) {
        this.pathPhoto = pathPhoto;
    }




}


